### ISSUE TITLE
Evaluation on COCO val set

### ISSUE THREAD

**Issue by NiranjanRavi1993** [kienduynguyen/BoxeR#20]
Hi  ,    
     Thank you for sharing the pretrained model.  In this issue : https://github.com/kienduynguyen/BoxeR/issues/12 , I was able to understand when we set it to "**val**" mode, a JSON file would be generated. 
     But when I execute, 
     python tools/run.py --config e2edet/config/COCO-Detection/boxer2d_R_50_3x.yaml --model boxer2d --task detection training.run_type=val     
     I have a couple of questions: 
     
     1. I do not get a JSON file generated. Is there any function I have to enable for it? 
     2. Which parameter in "**yaml**" file has to be modified to validate the pre-trained checkpoint?  
     3. The pre-trained model is in .pth format and whereas when I train the network I get .ckpt file? 
     
     It would be helpful to get your inputs on this.   
     Thank you.

**Comment by kienduynguyen** [comment]
1. If you want to generate the json file. Please set the run_type=test
2. In order to validate a checkpoint, you should set the resume_file to point to your checkpoint and run run_type=val
3. The .ckpt file contains optimizer states and other parameters to resume the training while the .pth contains only weights. You will get .pth file when you finalize the training process.
